import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import CustomProviders from "@cd/components/providers.component";
import { ThemeProvider } from "@cd/context/theme.context";
import { Layout } from "antd";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <ThemeProvider>
          <AntdRegistry>
            <CustomProviders>
              <Layout>{children}</Layout>
            </CustomProviders>
          </AntdRegistry>
        </ThemeProvider>
      </body>
    </html>
  );
}
